server:
  port: 8191
  
######Primary Mongo DB###########
spring:
  data:
    mongodb:
      uri: 
      database: orders #creates if it doesn't exist
      
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cpc
      
      