server:
  port: 8192
  
spring:
  data:
    mongodb:
      uri: 
      database: inventory #creates if it doesn't exist
      
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cpc